name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - requests=2.32.3
  - pip=24.3.1
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - mlflow=2.18.0
  - pip:
      - wandb==0.18.7