name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pandas=2.2.3
  - pip=24.3.1
  - scikit-learn=1.5.2
  - matplotlib=3.9.2
  - plotly=5.24.1
  - pillow=11.0.0
  - mlflow=2.18.0
  - pip:
      - wandb==0.18.7